let test1 = 'abcdf';
let test2 = 123;
let test3 = true;
let test4 = {};
let test5 = [];
let test6;
let test7 = {"abcdef": 123};
let test8 = ["abcdef", 123];
let test9 = () => 'abcdef';
let test10 = null;
let test11 = 0 / 0;

console.log(typeof test1);
console.log(typeof test2);
console.log(typeof test3);
console.log(typeof test4);
console.log(typeof test5);
console.log(typeof test6);
console.log(typeof test7);
console.log(typeof test8);
console.log(typeof test9);
console.log(typeof test10);
console.log(typeof test11);
